// Copyright (c) 2017-present Mattermost, Inc. All Rights Reserved.
// See License.txt for license information.

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	mattermostv1beta1 "github.com/mattermost/mattermost-operator/apis/mattermost/v1beta1"
	versioned "github.com/mattermost/mattermost-operator/pkg/client/v1beta1/clientset/versioned"
	internalinterfaces "github.com/mattermost/mattermost-operator/pkg/client/v1beta1/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/mattermost/mattermost-operator/pkg/client/v1beta1/listers/mattermost/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AgentInformer provides access to a shared informer and lister for
// Agents.
type AgentInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.AgentLister
}

type agentInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAgentInformer constructs a new informer for Agent type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAgentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAgentInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAgentInformer constructs a new informer for Agent type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAgentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MattermostV1beta1().Agents(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MattermostV1beta1().Agents(namespace).Watch(context.TODO(), options)
			},
		},
		&mattermostv1beta1.Agent{},
		resyncPeriod,
		indexers,
	)
}

func (f *agentInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAgentInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *agentInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&mattermostv1beta1.Agent{}, f.defaultInformer)
}

func (f *agentInformer) Lister() v1beta1.AgentLister {
	return v1beta1.NewAgentLister(f.Informer().GetIndexer())
}
