{
 "title": "Mattermost Collapsed Reply Threads Performance",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(mattermost_system_server_start_time, namespace)"
    }
   },
   {
    "name": "server",
    "label": "server",
    "query": {
     "query": "label_values(mattermost_system_server_start_time{namespace=\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GetThreadsForUser duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.99,\n  sum by (le,instance)(\n    rate(mattermost_db_store_time_bucket{pod=~\"$server\",method=\"ThreadStore.GetThreadsForUser\"}[5m])\n  )\n)",
     "legendFormat": "p99-{{instance}}"
    },
    {
     "expr": "histogram_quantile (\n  0.50,\n  sum by (le,instance)(\n    rate(mattermost_db_store_time_bucket{pod=~\"$server\",method=\"ThreadStore.GetThreadsForUser\"}[5m])\n  )\n)",
     "legendFormat": "p50-{{instance}}"
    }
   ]
  },
  {
   "title": "GetThreadsForUser Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mattermost_db_store_time_count{pod=~\"$server\",method=\"ThreadStore.GetThreadsForUser\"}[1m])) by (instance)",
     "legendFormat": "count-{{instance}}"
    },
    {
     "expr": "sum(rate(mattermost_db_store_time_count{pod=~\"$server\",method=\"ThreadStore.GetThreadsForUser\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "MarkAllAsReadByChannels duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.99,\n  sum by (le,instance)(\n    rate(mattermost_db_store_time_bucket{pod=~\"$server\",method=\"ThreadStore.MarkAllAsReadByChannels\"}[5m])\n  )\n)",
     "legendFormat": "p99-{{instance}}"
    },
    {
     "expr": "histogram_quantile (\n  0.50,\n  sum by (le,instance)(\n    rate(mattermost_db_store_time_bucket{pod=~\"$server\",method=\"ThreadStore.MarkAllAsReadByChannels\"}[5m])\n  )\n)",
     "legendFormat": "p50-{{instance}}"
    }
   ]
  },
  {
   "title": "MarkAllAsReadByChannels Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mattermost_db_store_time_count{pod=~\"$server\",method=\"ThreadStore.MarkAllAsReadByChannels\"}[1m])) by (instance)",
     "legendFormat": "count-{{instance}}"
    },
    {
     "expr": "sum(rate(mattermost_db_store_time_count{pod=~\"$server\",method=\"ThreadStore.MarkAllAsReadByChannels\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}