{
 "title": "Mattermost Performance KPI Metrics",
 "tags": [
  "mattermost",
  "mattermost-perf"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(mattermost_system_server_start_time, namespace)"
    }
   },
   {
    "name": "server",
    "label": "server",
    "query": "label_values(mattermost_system_server_start_time{namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Max CPU utilization rate (%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(irate(mattermost_process_cpu_seconds_total{pod=~\"$server\"}[1m])* 100)"
    }
   ]
  },
  {
   "title": "Number of messages / min",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(mattermost_post_total{pod=~\"$server\"}[1m]))"
    }
   ]
  },
  {
   "title": "Number of API errors / min",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(mattermost_http_errors_total{pod=~\"$server\"}[1m]))"
    }
   ]
  },
  {
   "title": "Number of connected devices",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(mattermost_http_websockets_total{pod=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Number of master DB conns",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(mattermost_db_master_connections_total{pod=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Server memory usage (in MB)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(go_memstats_alloc_bytes{pod=~\"$server\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Number of Messages per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "irate(mattermost_post_total{pod=~\"$server\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(mattermost_post_total{pod=~\"$server\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of API Errors per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "irate(mattermost_http_errors_total{pod=~\"$server\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(mattermost_http_errors_total{pod=~\"$server\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Mean API Request Time (in milliseconds)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds (ms)" }
   ],
   "targets": [
    {
     "expr": "1000.0 * rate(mattermost_api_time_sum{pod=~\"$server\"}[1m]) /   rate(mattermost_api_time_count{pod=~\"$server\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Connections to Master Database",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "mattermost_db_master_connections_total{pod=~\"$server\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(mattermost_db_master_connections_total{pod=~\"$server\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Mean Cluster Request Time (in milliseconds)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds (ms)" }
   ],
   "targets": [
    {
     "expr": "1000.0 * rate(mattermost_cluster_cluster_request_duration_seconds_sum{pod=~\"$server\"}[1m]) /   rate(mattermost_cluster_cluster_request_duration_seconds_count{pod=~\"$server\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Connections to Read Replica Databases",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "mattermost_db_read_replica_connections_total{pod=~\"$server\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "sum(mattermost_db_read_replica_connections_total{pod=~\"$server\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU Utilization Rate (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Utilization Rate (%)" }
   ],
   "targets": [
    {
     "expr": "irate(mattermost_process_cpu_seconds_total{pod=~\"$server\"}[1m])* 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Go Routines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{pod=~\"$server\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(go_goroutines{pod=~\"$server\"})",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}