{
 "title": "Mattermost Calls - Performance Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "calls", "label": "calls-instance", "query": { "query": "label_values(instance)" } },
   { "name": "rtcd", "label": "rtcd-instance", "query": { "query": "label_values(instance)" } },
   { "name": "rtcd_metrics_port", "query": "${VAR_RTCD_METRICS_PORT}" },
   { "name": "calls_metrics_port", "query": "${VAR_CALLS_METRICS_PORT}" },
   { "name": "offloader", "label": "offloader-instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(irate(mattermost_plugin_calls_process_cpu_seconds_total{instance=~\"$calls:$calls_metrics_port\"}[2m])* 100) by (instance)",
     "legendFormat": "calls - {{ instance }}"
    },
    {
     "expr": "avg(irate(rtcd_process_cpu_seconds_total{instance=~\"$rtcd:$rtcd_metrics_port\"}[2m])* 100) by (instance)",
     "legendFormat": "rtcd - {{ instance }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=~\"$calls:$calls_metrics_port\", job=\"calls\"}",
     "legendFormat": "calls - {{ instance }} - heap"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=~\"$rtcd:$rtcd_metrics_port\"}",
     "legendFormat": "rtcd - {{ instance }} - heap"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=~\"$calls:$calls_metrics_port\", job=\"calls\"}",
     "legendFormat": "calls - {{ instance }} - stack"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=~\"$rtcd:$rtcd_metrics_port\"}",
     "legendFormat": "rtcd - {{ instance }} - stack"
    }
   ]
  },
  {
   "title": "WebSocket Events (calls plugin)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mattermost_plugin_calls_websocket_events_total{instance=~\"$calls:$calls_metrics_port\"}[2m])) by (instance, type)",
     "legendFormat": "calls - {{ type }}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(go_goroutines{instance=~\"$calls:$calls_metrics_port\"}) by (instance)",
     "legendFormat": "calls - {{ instance }}"
    },
    {
     "expr": "sum(go_goroutines{instance=~\"$rtcd:$rtcd_metrics_port\"}) by (instance)",
     "legendFormat": "rtcd - {{ instance }}"
    }
   ]
  },
  {
   "title": "WebSocket Connections (rtcd)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rtcd_ws_connections_total{instance=~\"$rtcd:$rtcd_metrics_port\"}",
     "legendFormat": "rtcd - {{ instance }}"
    }
   ]
  },
  {
   "title": "WebSocket Messages (rtcd)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(rtcd_ws_messages_total{instance=~\"$rtcd:$rtcd_metrics_port\"}[2m])) by (type, instance)",
     "legendFormat": "rtcd - {{type}} - {{ instance}}"
    }
   ]
  },
  {
   "title": "App Handlers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(mattermost_plugin_calls_app_handlers_time_bucket{instance=~\"$calls:$calls_metrics_port\"}[2m])) by (handler,le))",
     "legendFormat": "Handler time p99-{{handler}}"
    },
    {
     "expr": "sum(rate(mattermost_plugin_calls_app_handlers_time_sum{instance=~\"$calls:$calls_metrics_port\"}[2m])) by (handler) / sum(rate(mattermost_plugin_calls_app_handlers_time_count{instance=~\"$calls:$calls_metrics_port\"}[2m])) by (handler)",
     "legendFormat": "Handler time avg-{{handler}}"
    }
   ]
  },
  {
   "title": "Store Methods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(mattermost_plugin_calls_store_methods_time_bucket{instance=~\"$calls:$calls_metrics_port\"}[2m])) by (method,le))",
     "legendFormat": "Handler time p99-{{method}}"
    },
    {
     "expr": "sum(rate(mattermost_plugin_calls_store_methods_time_sum{instance=~\"$calls:$calls_metrics_port\"}[2m])) by (method) / sum(rate(mattermost_plugin_calls_store_methods_time_count{instance=~\"$calls:$calls_metrics_port\"}[2m])) by (method)",
     "legendFormat": "Handler time avg-{{method}}"
    }
   ]
  },
  {
   "title": "DB Connections (writer)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(go_sql_in_use_connections{instance=~\"$calls:$calls_metrics_port\", job=\"calls\"}) by (instance)",
     "legendFormat": "In Use - {{ instance }}"
    },
    {
     "expr": "sum(go_sql_idle_connections{instance=~\"$calls:$calls_metrics_port\", job=\"calls\"}) by (instance)",
     "legendFormat": "Idle - {{ instance }}"
    },
    {
     "expr": "sum(go_sql_open_connections{instance=~\"$calls:$calls_metrics_port\", job=\"calls\"}) by (instance)",
     "legendFormat": "Open - {{ instance }}"
    }
   ]
  },
  {
   "title": "DB Connections Wait",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(go_sql_wait_duration_seconds_total{instance=~\"$calls:$calls_metrics_port\", job=\"calls\"}[2m])) by (instance)",
     "legendFormat": "total - {{instance}}"
    },
    {
     "expr": "sum(rate(go_sql_wait_duration_seconds_total{instance=~\"$calls:$calls_metrics_port\", job=\"calls\"}[2m])) by (instance) / sum(rate(go_sql_wait_count_total{instance=~\"$calls:$calls_metrics_port\", job=\"calls\"}[2m])) by (instance)",
     "legendFormat": "avg - {{instance}}"
    }
   ]
  },
  {
   "title": "Cluster Mutexes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(mattermost_plugin_calls_cluster_mutex_grab_time_bucket{instance=~\"$calls:$calls_metrics_port\"}[2m])) by (group,le))",
     "legendFormat": "Grab time p99-{{group}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(mattermost_plugin_calls_cluster_mutex_locked_time_bucket{instance=~\"$calls:$calls_metrics_port\"}[2m])) by (group,le))",
     "legendFormat": "Lock time p99-{{group}}"
    },
    {
     "expr": "sum(rate(mattermost_plugin_calls_cluster_mutex_grab_time_sum{instance=~\"$calls:$calls_metrics_port\"}[2m])) by (group) / sum(rate(mattermost_plugin_calls_cluster_mutex_grab_time_count{instance=~\"$calls:$calls_metrics_port\"}[2m])) by (group)",
     "legendFormat": "Grab time avg-{{group}}"
    },
    {
     "expr": "sum(rate(mattermost_plugin_calls_cluster_mutex_locked_time_sum{instance=~\"$calls:$calls_metrics_port\"}[2m])) by (group) / sum(rate(mattermost_plugin_calls_cluster_mutex_locked_time_count{instance=~\"$calls:$calls_metrics_port\"}[2m])) by (group)",
     "legendFormat": "Lock time avg-{{group}}"
    },
    {
     "expr": "sum(increase(mattermost_plugin_calls_cluster_mutex_lock_retries_total{instance=~\"$calls:$calls_metrics_port\"}[2m])) by (group)",
     "legendFormat": "Retries {{group}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(mattermost_plugin_calls_cluster_mutex_local_grab_time_bucket{instance=~\"$calls:$calls_metrics_port\"}[2m])) by (group,le))",
     "legendFormat": "Grab time local p99-{{group}}"
    },
    {
     "expr": "sum(rate(mattermost_plugin_calls_cluster_mutex_local_grab_time_sum{instance=~\"$calls:$calls_metrics_port\"}[2m])) by (group) / sum(rate(mattermost_plugin_calls_cluster_mutex_local_grab_time_count{instance=~\"$calls:$calls_metrics_port\"}[2m])) by (group)",
     "legendFormat": "Grab local time avg-{{group}}"
    }
   ]
  },
  { "title": "RTC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "RTC Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mattermost_plugin_calls_rtc_sessions_total{instance=~\"$calls:$calls_metrics_port\"}) by (instance)",
     "legendFormat": "calls - {{ instance }}"
    },
    {
     "expr": "sum(rtcd_rtc_sessions_total{instance=~\"$rtcd:$rtcd_metrics_port\"}) by (instance)",
     "legendFormat": "rtcd - {{ instance }}"
    }
   ]
  },
  {
   "title": "RTC Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(mattermost_plugin_calls_rtc_errors_total{instance=~\"$calls:$calls_metrics_port\"}[2m])) by (type, instance)",
     "legendFormat": "calls - {{ type }}"
    },
    {
     "expr": "sum(increase(rtcd_rtc_errors_total{instance=~\"$rtcd:$rtcd_metrics_port\"}[2m])) by (type, instance)",
     "legendFormat": "rtcd - {{ type }}"
    }
   ]
  },
  {
   "title": "RTP Tracks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mattermost_plugin_calls_rtc_rtp_tracks_total{instance=~\"$calls:$calls_metrics_port\"}) by (instance, direction, type)",
     "legendFormat": "{{ instance }} - {{direction}} - {{type}}"
    },
    {
     "expr": "sum(rtcd_rtc_rtp_tracks_total{instance=~\"$rtcd:$rtcd_metrics_port\"}) by (instance, direction, type)",
     "legendFormat": "rtcd - {{ instance }} - {{direction}} - {{type}}"
    }
   ]
  },
  {
   "title": "RTP Tracks Writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(rtcd_rtc_rtp_tracks_writes_time_sum{instance=~\"$rtcd:$rtcd_metrics_port\"}[2m]) / (rate(rtcd_rtc_rtp_tracks_writes_time_count{instance=~\"$rtcd:$rtcd_metrics_port\"}[2m]) > 0)",
     "legendFormat": "avg - {{type}} - {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(rtcd_rtc_rtp_tracks_writes_time_bucket{instance=~\"$rtcd:$rtcd_metrics_port\"}[2m])) by (type,le,instance))",
     "legendFormat": "p99 - {{type}} - {{instance}}"
    }
   ]
  },
  {
   "title": "RTC Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(mattermost_plugin_calls_rtc_conn_states_total{instance=~\"$calls:$calls_metrics_port\"}[2m])) by (instance, type)",
     "legendFormat": "{{ instance }} - {{ type }}"
    },
    {
     "expr": "sum(increase(rtcd_rtc_conn_states_total{instance=~\"$rtcd:$rtcd_metrics_port\"}[2m])) by (instance, type)",
     "legendFormat": "rtcd - {{ instance }} - {{ type }}"
    }
   ]
  },
  {
   "title": "RTC Connection Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(rtcd_rtc_connection_time_sum{instance=~\"$rtcd:$rtcd_metrics_port\"}[2m]) / (rate(rtcd_rtc_connection_time_count{instance=~\"$rtcd:$rtcd_metrics_port\"}[2m]) > 0)",
     "legendFormat": "avg - {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(rtcd_rtc_connection_time_bucket{instance=~\"$rtcd:$rtcd_metrics_port\"}[2m])) by (le,instance))",
     "legendFormat": "p99  - {{instance}}"
    }
   ]
  },
  {
   "title": "Signaling Lock Grab Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(rtcd_rtc_signaling_lock_grab_time_sum{instance=~\"$rtcd:$rtcd_metrics_port\"}[2m]) / (rate(rtcd_rtc_signaling_lock_grab_time_count{instance=~\"$rtcd:$rtcd_metrics_port\"}[2m]) > 0)",
     "legendFormat": "avg - {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(rtcd_rtc_signaling_lock_grab_time_bucket{instance=~\"$rtcd:$rtcd_metrics_port\"}[2m])) by (le,instance))",
     "legendFormat": "p99  - {{instance}}"
    }
   ]
  },
  {
   "title": "Signaling Lock Locked Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(rtcd_rtc_signaling_lock_locked_time_sum{instance=~\"$rtcd:$rtcd_metrics_port\"}[2m]) / (rate(rtcd_rtc_signaling_lock_locked_time_count{instance=~\"$rtcd:$rtcd_metrics_port\"}[2m]) > 0)",
     "legendFormat": "avg - {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(rtcd_rtc_signaling_lock_locked_time_bucket{instance=~\"$rtcd:$rtcd_metrics_port\"}[2m])) by (type,le,instance))",
     "legendFormat": "p99  - {{instance}}"
    }
   ]
  },
  { "title": "RTC - Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "ICE Candidates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "sum(mattermost_plugin_calls_client_ice_candidate_pairs_total{instance=~\"$calls:$calls_metrics_port\"}) by (state, local_type, remote_type, local_protocol, remote_protocol)",
     "legendFormat": "{{state}} - {{local_type}} - {{remote_type}} - {{remote_protocol}}"
    }
   ]
  },
  {
   "title": "Round Trip Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(rtcd_rtc_client_rtt_sum{instance=~\"$rtcd:$rtcd_metrics_port\"}[2m]) / (rate(rtcd_rtc_client_rtt_count{instance=~\"$rtcd:$rtcd_metrics_port\"}[2m]) > 0)",
     "legendFormat": "avg - {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(rtcd_rtc_client_rtt_bucket{instance=~\"$rtcd:$rtcd_metrics_port\"}[2m])) by (le,instance))",
     "legendFormat": "p99 - {{instance}}"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(rtcd_rtc_client_jitter_sum{instance=~\"$rtcd:$rtcd_metrics_port\"}[2m]) / (rate(rtcd_rtc_client_jitter_count{instance=~\"$rtcd:$rtcd_metrics_port\"}[2m]) > 0)",
     "legendFormat": "avg - {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(rtcd_rtc_client_jitter_bucket{instance=~\"$rtcd:$rtcd_metrics_port\"}[2m])) by (le,instance))",
     "legendFormat": "p99 - {{instance}}"
    }
   ]
  },
  {
   "title": "Loss Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(rtcd_rtc_client_loss_rate_sum{instance=~\"$rtcd:$rtcd_metrics_port\"}[2m]) / (rate(rtcd_rtc_client_loss_rate_count{instance=~\"$rtcd:$rtcd_metrics_port\"}[2m]) > 0)",
     "legendFormat": "avg - {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(rtcd_rtc_client_loss_rate_bucket{instance=~\"$rtcd:$rtcd_metrics_port\"}[2m])) by (le,instance))",
     "legendFormat": "p99 - {{instance}}"
    }
   ]
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "UDP Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_netstat_Udp_InDatagrams{instance=~\"$rtcd:9100\"}[2m])",
     "legendFormat": "rtcd - {{ instance }} - In - IPv4"
    },
    {
     "expr": "rate(node_netstat_Udp_OutDatagrams{instance=~\"$rtcd:9100\"}[2m])",
     "legendFormat": "rtcd - {{ instance }} - Out - IPv4"
    },
    {
     "expr": "rate(node_netstat_Udp_InErrors{instance=~\"$rtcd:9100\"}[2m])",
     "legendFormat": "rtcd - {{ instance }} - Errors - IPv4"
    },
    {
     "expr": "rate(node_netstat_Udp_InDatagrams{instance=~\"$calls:9100\"}[2m])",
     "legendFormat": "calls  - {{ instance }} - In - IPv4"
    },
    {
     "expr": "rate(node_netstat_Udp_OutDatagrams{instance=~\"$calls:9100\"}[2m])",
     "legendFormat": "calls - {{ instance }} - Out - IPv4"
    },
    {
     "expr": "rate(node_netstat_Udp_InErrors{instance=~\"$calls:9100\"}[2m])",
     "legendFormat": "calls - {{ instance }} - Errors - IPv4"
    },
    {
     "expr": "rate(node_netstat_Udp6_InDatagrams{instance=~\"$rtcd:9100\"}[2m])",
     "legendFormat": "rtcd - {{ instance }} - In - IPv6"
    },
    {
     "expr": "rate(node_netstat_Udp6_OutDatagrams{instance=~\"$rtcd:9100\"}[2m])",
     "legendFormat": "rtcd - {{ instance }} - Out - IPv6"
    },
    {
     "expr": "rate(node_netstat_Udp6_InErrors{instance=~\"$rtcd:9100\"}[2m])",
     "legendFormat": "rtcd - {{ instance }} - Errors - IPv6"
    }
   ]
  },
  {
   "title": "TCP Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "targets": [
    {
     "expr": "node_sockstat_TCP_inuse{instance=~\"$rtcd:9100\"}",
     "legendFormat": "rtcd - {{ instance }} -  Connections - IPv4"
    },
    {
     "expr": "node_sockstat_TCP6_inuse{instance=~\"$rtcd:9100\"}",
     "legendFormat": "rtcd - {{ instance }} -  Connections - IPv6"
    },
    {
     "expr": "rate(node_netstat_Tcp_InErrs{instance=~\"$rtcd:9100\"}[2m])",
     "legendFormat": "rtcd - {{ instance }} -  Errors"
    },
    {
     "expr": "rate(node_netstat_TcpExt_TCPTimeouts{instance=~\"$rtcd:9100\"}[2m])",
     "legendFormat": "rtcd - {{ instance }} -  Timeouts"
    },
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{instance=~\"$rtcd:9100\"}[2m])",
     "legendFormat": "rtcd - {{ instance }} -  Retransmissions"
    }
   ]
  },
  {
   "title": "Network RX/TX Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "(sum(rate(node_network_transmit_bytes_total{instance=~\"$rtcd:9100\"}[2m])) by (instance))*8",
     "legendFormat": "rtcd - TX Rate {{ instance }}"
    },
    {
     "expr": "(sum(rate(node_network_receive_bytes_total{instance=~\"$rtcd:9100\"}[2m])) by (instance))*8",
     "legendFormat": "rtcd - RX Rate {{ instance }}"
    },
    {
     "expr": "(sum(rate(node_network_transmit_bytes_total{instance=~\"$calls:9100\"}[2m])) by (instance))*8",
     "legendFormat": "calls - TX Rate {{ instance }}"
    },
    {
     "expr": "(sum(rate(node_network_receive_bytes_total{instance=~\"$calls:9100\"}[2m])) by (instance))*8",
     "legendFormat": "calls - RX Rate {{ instance }}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 } },
  {
   "title": "CPU Load (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{instance=~\"$rtcd:9100\",mode=\"idle\"}[1m])) by (instance)",
     "legendFormat": "Used {{instance}}"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$rtcd:9100\",mode=\"system\"}[1m])) by (instance)",
     "legendFormat": "System {{instance}}"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$rtcd:9100\",mode=\"idle\"}[1m])) by (instance)",
     "legendFormat": "Idle {{instance}}"
    },
    {
     "expr": "100 - 100 * avg(irate(node_cpu_seconds_total{instance=~\"$rtcd:9100\",mode=\"idle\"}[1m])) by (instance)",
     "legendFormat": "Used (pct) {{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$rtcd:9100\"} - node_memory_MemAvailable_bytes{instance=~\"$rtcd:9100\"}",
     "legendFormat": "Used {{ instance }}"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$rtcd:9100\"}",
     "legendFormat": "Total {{ instance }}"
    },
    {
     "expr": "((node_memory_MemTotal_bytes{instance=~\"$rtcd:9100\"} - node_memory_MemAvailable_bytes{instance=~\"$rtcd:9100\"}) / node_memory_MemTotal_bytes{instance=~\"$rtcd:9100\"}) * 100",
     "legendFormat": "Used (pct) {{ instance }}"
    }
   ]
  },
  { "title": "Offloader", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "100 - 100 * avg(irate(node_cpu_seconds_total{instance=~\"$offloader:9100\",mode=\"idle\"}[2m])) by (instance)",
     "legendFormat": "offloader - {{ instance }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$offloader:9100\"} - node_memory_MemAvailable_bytes{instance=~\"$offloader:9100\"}",
     "legendFormat": "mem used - {{ instance }}"
    }
   ]
  },
  {
   "title": "Live Captions Audio Length (ms)",
   "type": "heatmap",
   "description": "The size of the chunks of audio being processed. If everything is working well, should be == tick, which is default 2000ms.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 134 },
   "targets": [
    {
     "expr": "sum by(le) (increase(mattermost_plugin_calls_jobs_live_captions_new_audio_len_ms_bucket{instance=~\"$calls:$calls_metrics_port\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Length of time to process audio chunks",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "chunks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (increase(mattermost_plugin_calls_jobs_live_captions_new_audio_len_ms_bucket{instance=~\"$calls:$calls_metrics_port\"}[1h]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Windows dropped + transcriber buf full",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
   "targets": [
    {
     "expr": "sum by(job) (increase(mattermost_plugin_calls_jobs_live_captions_window_dropped{instance=~\"$calls:$calls_metrics_port\"}[$__rate_interval]))",
     "legendFormat": "windows dropped"
    },
    {
     "expr": "sum by(job) (increase(mattermost_plugin_calls_jobs_live_captions_transcriber_buf_full{instance=~\"$calls:$calls_metrics_port\"}[$__rate_interval]))",
     "legendFormat": "transcriber buf full"
    },
    {
     "expr": "sum by(job) (rate(mattermost_plugin_calls_jobs_live_captions_pktPayloadCh_buf_full{instance=~\"$calls:$calls_metrics_port\"}[$__rate_interval]))",
     "legendFormat": "packetChBuffFull"
    }
   ]
  },
  {
   "title": "Windows dropped + transcriber buf full",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 142 },
   "targets": [
    {
     "expr": "sum by(job) (increase(mattermost_plugin_calls_jobs_live_captions_window_dropped{instance=~\"$calls:$calls_metrics_port\"}[15m]))",
     "legendFormat": "windows dropped"
    },
    {
     "expr": "sum by(job) (increase(mattermost_plugin_calls_jobs_live_captions_transcriber_buf_full{instance=~\"$calls:$calls_metrics_port\"}[15m]))",
     "legendFormat": "transcriber buf full"
    },
    {
     "expr": "sum by(job) (rate(mattermost_plugin_calls_jobs_live_captions_pktPayloadCh_buf_full{instance=~\"$calls:$calls_metrics_port\"}[15m]))",
     "legendFormat": "packetChBuffFull"
    }
   ]
  }
 ]
}