apiVersion: mattermost.com/v1alpha1
kind: ClusterInstallation
metadata:
  name: mm-example-full # Name of your cluster as shown in Kubernetes.
spec:
  image: mattermost/mattermost-enterprise-edition # Docker image for the app servers.
  version: 5.19.1 # Docker tag for the image.
  size: 5000users # Size of the Mattermost installation, typically based on the number of users. Automatically sets the replica and resource limits for Minio, databaes and app servers based on the number provided here. Accepts 100users, 1000users, 5000users, 10000users, or 25000users. Manually setting replicas or resources will override the values set by 'size'.
  useServiceLoadBalancer: true # Set to true to use AWS or Azure load balancers instead of an NGINX controller.
  serviceAnnotations: {} # Service annotations to use with AWS or Azure load balancers.
  ingressName: example.mattermost-example.com # Set to your hostname, e.g. example.mattermost-example.com. Required when using an Ingress controller. Ignored if useServiceLoadBalancer is true.
  database:
    type: mysql # Supports "mysql". Ignored if externalSecret is set.
    externalSecret: "" # Set to the name of a Kubernetes secret that contains the password to your external MySQL database. MySQL username must be "root".
    storageSize: 50Gi # Set the file storage size to be used by the database. Ignored if externalSecret is set.
  minio:
    storageSize: 50Gi # Set the file storage size to be used by Minio.
  elasticSearch:
    host: "" # Hostname Elasticsearch can be accessed at.
    username: "" # Username to log into Elasticsearch.
    password: "" # Password to log into Elasticsearch.
  nodeSelector: {} # See https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector.
  affinity: {} # See https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity.
