// Copyright (c) 2017-present Mattermost, Inc. All Rights Reserved.
// See License.txt for license information.

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/mattermost/mattermost-operator/apis/mattermost/v1beta1"
	scheme "github.com/mattermost/mattermost-operator/pkg/client/v1beta1/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AgentsGetter has a method to return a AgentInterface.
// A group's client should implement this interface.
type AgentsGetter interface {
	Agents(namespace string) AgentInterface
}

// AgentInterface has methods to work with Agent resources.
type AgentInterface interface {
	Create(ctx context.Context, agent *v1beta1.Agent, opts v1.CreateOptions) (*v1beta1.Agent, error)
	Update(ctx context.Context, agent *v1beta1.Agent, opts v1.UpdateOptions) (*v1beta1.Agent, error)
	UpdateStatus(ctx context.Context, agent *v1beta1.Agent, opts v1.UpdateOptions) (*v1beta1.Agent, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.Agent, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.AgentList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.Agent, err error)
	AgentExpansion
}

// agents implements AgentInterface
type agents struct {
	client rest.Interface
	ns     string
}

// newAgents returns a Agents
func newAgents(c *MattermostV1beta1Client, namespace string) *agents {
	return &agents{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the agent, and returns the corresponding agent object, and an error if there is any.
func (c *agents) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.Agent, err error) {
	result = &v1beta1.Agent{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("agents").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Agents that match those selectors.
func (c *agents) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.AgentList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.AgentList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("agents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested agents.
func (c *agents) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("agents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a agent and creates it.  Returns the server's representation of the agent, and an error, if there is any.
func (c *agents) Create(ctx context.Context, agent *v1beta1.Agent, opts v1.CreateOptions) (result *v1beta1.Agent, err error) {
	result = &v1beta1.Agent{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("agents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(agent).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a agent and updates it. Returns the server's representation of the agent, and an error, if there is any.
func (c *agents) Update(ctx context.Context, agent *v1beta1.Agent, opts v1.UpdateOptions) (result *v1beta1.Agent, err error) {
	result = &v1beta1.Agent{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("agents").
		Name(agent.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(agent).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *agents) UpdateStatus(ctx context.Context, agent *v1beta1.Agent, opts v1.UpdateOptions) (result *v1beta1.Agent, err error) {
	result = &v1beta1.Agent{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("agents").
		Name(agent.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(agent).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the agent and deletes it. Returns an error if one occurs.
func (c *agents) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("agents").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *agents) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("agents").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched agent.
func (c *agents) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.Agent, err error) {
	result = &v1beta1.Agent{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("agents").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
