# This file contains MinIO manifest than can be applied locally in the cluster and
# treated as an external file store for Mattermost instance.
# This manifest is prepared for development and testing purposes and should not be used in production environment.

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: minio
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2021-10-27T16-29-42Z
          args: ['server', '/data', '--console-address', ':9001']
          ports:
            - name: minio
              containerPort: 9000
          volumeMounts:
            - name: s3-pv-storage
              mountPath: /data
          env:
            - name: MINIO_SERVER_URL
              value: https://minio.example.com
            - name: MINIO_BROWSER_REDIRECT_URL
              value: https://console.minio.example.com
            - name: MINIO_IDENTITY_OPENID_CONFIG_URL
              value: https://keycloak.example.com/auth/realms/home/.well-known/openid-configuration
            - name: MINIO_IDENTITY_OPENID_CLIENT_ID
              value: minio
            - name: MINIO_IDENTITY_OPENID_CLIENT_SECRET
              value: secret
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: MINIO_ROOT_PASSWORD
      volumes:
        - name: s3-pv-storage
          hostPath:
            path: /minio-data
---

apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  ports:
    - protocol: TCP
      name: minio
      port: 9000
    - protocol: TCP
      name: minio-console
      port: 9001
  selector:
    app: minio
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: minio
  labels:
    app: minio
data:
  MINIO_ROOT_USER: bXktYWNjZXNzLWtleQ==
  MINIO_ROOT_PASSWORD: bXlYWFh4eHgvc2VjcmV0WFhYWHh4eC9rZXlYWHh4eA==
