# Secrets that can be referenced in Mattermost CR.

apiVersion: v1
data:
  DB_CONNECTION_STRING: cG9zdGdyZXM6Ly9wb3N0Z3JlczpwYXNzd29yZEBwb3N0Z3Jlc3FsOjU0MzIvcG9zdGdyZXM/c3NsbW9kZT1kaXNhYmxl
kind: Secret
metadata:
  name: db-credentials
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: file-store-credentials
type: Opaque
data:
  accesskey: bXktYWNjZXNzLWtleQ==
  secretkey: bXlYWFh4eHgvc2VjcmV0WFhYWHh4eC9rZXlYWHh4eA==
