# permissions for end users to view mattermosts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mattermost-viewer-role
rules:
- apiGroups:
  - mattermost.mattermost.com
  resources:
  - mattermosts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mattermost.mattermost.com
  resources:
  - mattermosts/status
  verbs:
  - get
