{{- if .Values.mattermostOperator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mattermost-operator.name" . }}
spec:
  replicas: {{ .Values.mattermostOperator.replicas }}
  selector:
    matchLabels:
      name: {{ template "mattermost-operator.name" . }}
  template:
    metadata:
      labels:
        name: {{ template "mattermost-operator.name" . }}
    spec:
      containers:
      - args:
        - --enable-leader-election
        command:
        - /mattermost-operator
        env:
        - name: MAX_RECONCILING_INSTALLATIONS
          value: "{{ .Values.mattermostOperator.env.maxReconcilingInstallations }}"
        - name: REQUEUE_ON_LIMIT_DELAY
          value: "{{ .Values.mattermostOperator.env.requeuOnLimitDelay }}"
        image: "{{ .Values.mattermostOperator.image.repository }}:{{ .Values.mattermostOperator.image.tag }}"
        imagePullPolicy: "{{ .Values.mattermostOperator.image.pullPolicy }}"
        name: {{ template "mattermost-operator.name" . }}
      serviceAccountName: {{ template "mattermost-operator.fullname" . }}
{{- end }}
