// Copyright (c) 2017-present Mattermost, Inc. All Rights Reserved.
// See License.txt for license information.

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/mattermost/mattermost-operator/apis/mattermost/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// AgentLister helps list Agents.
// All objects returned here must be treated as read-only.
type AgentLister interface {
	// List lists all Agents in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.Agent, err error)
	// Agents returns an object that can list and get Agents.
	Agents(namespace string) AgentNamespaceLister
	AgentListerExpansion
}

// agentLister implements the AgentLister interface.
type agentLister struct {
	indexer cache.Indexer
}

// NewAgentLister returns a new AgentLister.
func NewAgentLister(indexer cache.Indexer) AgentLister {
	return &agentLister{indexer: indexer}
}

// List lists all Agents in the indexer.
func (s *agentLister) List(selector labels.Selector) (ret []*v1beta1.Agent, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.Agent))
	})
	return ret, err
}

// Agents returns an object that can list and get Agents.
func (s *agentLister) Agents(namespace string) AgentNamespaceLister {
	return agentNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// AgentNamespaceLister helps list and get Agents.
// All objects returned here must be treated as read-only.
type AgentNamespaceLister interface {
	// List lists all Agents in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.Agent, err error)
	// Get retrieves the Agent from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.Agent, error)
	AgentNamespaceListerExpansion
}

// agentNamespaceLister implements the AgentNamespaceLister
// interface.
type agentNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all Agents in the indexer for a given namespace.
func (s agentNamespaceLister) List(selector labels.Selector) (ret []*v1beta1.Agent, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.Agent))
	})
	return ret, err
}

// Get retrieves the Agent from the indexer for a given namespace and name.
func (s agentNamespaceLister) Get(name string) (*v1beta1.Agent, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("agent"), name)
	}
	return obj.(*v1beta1.Agent), nil
}
