// Copyright (c) 2017-present Mattermost, Inc. All Rights Reserved.
// See License.txt for license information.

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// MattermostListerExpansion allows custom methods to be added to
// MattermostLister.
type MattermostListerExpansion interface{}

// MattermostNamespaceListerExpansion allows custom methods to be added to
// MattermostNamespaceLister.
type MattermostNamespaceListerExpansion interface{}
