// Copyright (c) 2017-present Mattermost, Inc. All Rights Reserved.
// See License.txt for license information.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ClusterInstallationListerExpansion allows custom methods to be added to
// ClusterInstallationLister.
type ClusterInstallationListerExpansion interface{}

// ClusterInstallationNamespaceListerExpansion allows custom methods to be added to
// ClusterInstallationNamespaceLister.
type ClusterInstallationNamespaceListerExpansion interface{}
