## Append samples you want in your CSV to this file as resources ##
resources:
- mattermost.com_v1alpha1_mattermostrestoredb.yaml
- mattermost.com_v1alpha1_clusterinstallation.yaml
- installation.mattermost.com_v1beta1_mattermost.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
