apiVersion: v1
kind: ServiceAccount
metadata:
  name: mattermost-operator
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterinstallations.mattermost.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.state
    description: State of Mattermost
    name: State
    type: string
  - JSONPath: .status.image
    description: Image of Mattermost
    name: Image
    type: string
  - JSONPath: .status.version
    description: Version of Mattermost
    name: Version
    type: string
  - JSONPath: .status.endpoint
    description: Endpoint
    name: Endpoint
    type: string
  group: mattermost.com
  names:
    kind: ClusterInstallation
    listKind: ClusterInstallationList
    plural: clusterinstallations
    singular: clusterinstallation
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          description: 'Standard object’s metadata. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#metadata
            +k8s:openapi-gen=false'
          type: object
        spec:
          description: 'Specification of the desired behavior of the Mattermost cluster.
            More info: https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#spec-and-status'
          properties:
            affinity:
              description: If specified, affinity will define the pod's scheduling
                constraints
              type: object
            databaseType:
              properties:
                dbStorageSize:
                  description: Defines the storage size for the database. ie 50Gi
                  pattern: ^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$
                  type: string
                externalDatabaseSecret:
                  description: If the user want to use an external DB. This can be
                    inside the same k8s cluster or outside like AWS RDS.
                  type: string
                type:
                  type: string
              type: object
            elasticSearch:
              properties:
                host:
                  type: string
                password:
                  type: string
                username:
                  type: string
              type: object
            image:
              description: Image defines the ClusterInstallation Docker image.
              type: string
            ingressAnnotations:
              additionalProperties:
                type: string
              type: object
            ingressName:
              description: IngressName defines the name to be used when creating the
                ingress rules
              type: string
            mattermostLicenseSecret:
              description: Secret that contains the mattermost license
              type: string
            minioStorageSize:
              description: MinioStorageSize defines the storage size for minio. ie
                50Gi
              pattern: ^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$
              type: string
            nodeSelector:
              additionalProperties:
                type: string
              description: 'NodeSelector is a selector which must be true for the
                pod to fit on a node. Selector which must match a node''s labels for
                the pod to be scheduled on that node. More info: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/'
              type: object
            replicas:
              description: Replicas defines the number of Mattermost instances in
                a ClusterInstallation resource
              format: int32
              type: integer
            serviceAnnotations:
              additionalProperties:
                type: string
              type: object
            useServiceLoadBalancer:
              type: boolean
            version:
              description: Version defines the ClusterInstallation Docker image version.
              type: string
          required:
          - ingressName
          type: object
        status:
          description: 'Most recent observed status of the Mattermost cluster. Read-only.
            Not included when requesting from the apiserver, only from the Mattermost
            Operator API itself. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#spec-and-status'
          properties:
            endpoint:
              description: The endpoint to access the Mattermost instance
              type: string
            image:
              description: The image running on the pods in the Mattermost instance
              type: string
            replicas:
              description: Total number of non-terminated pods targeted by this Mattermost
                deployment
              format: int32
              type: integer
            state:
              description: Represents the running state of the Mattermost instance
              type: string
            updatedReplicas:
              description: Total number of non-terminated pods targeted by this Mattermost
                deployment that are running with the desired image.
              format: int32
              type: integer
            version:
              description: The version currently running in the Mattermost instance
              type: string
          type: object
      required:
      - spec
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: mattermost-operator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - extensions
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - get
  - create
  - list
  - delete
  - watch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - mattermost-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - mattermost.com
  resources:
  - '*'
  - clusterinstallations
  verbs:
  - '*'
- apiGroups:
  - mysql.presslabs.org
  resources:
  - mysqlbackups
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - mysql.presslabs.org
  resources:
  - mysqlclusters
  - mysqlclusters/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - miniocontroller.min.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - minio.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - get
  - create
  - list
  - delete
  - watch
  - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mattermost-operator
subjects:
- kind: ServiceAccount
  name: mattermost-operator
  namespace: mattermost-operator
roleRef:
  kind: ClusterRole
  name: mattermost-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mattermost-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mattermost-operator
  template:
    metadata:
      labels:
        name: mattermost-operator
    spec:
      serviceAccountName: mattermost-operator
      containers:
        - name: mattermost-operator
          image: mattermost/mattermost-operator:latest
          command:
          - mattermost-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "mattermost-operator"
