# Example Secret for External MySQL Database
#
# This secret demonstrates the correct format for external database configuration.
# 
# Key differences:
# - DB_CONNECTION_STRING: Must include the mysql:// or postgres:// protocol prefix (used for MM_CONFIG)
# - MM_SQLSETTINGS_DATASOURCE: Should NOT include the protocol prefix (raw DSN format)
#
# The operator will automatically use the appropriate key for each environment variable.
---
apiVersion: v1
kind: Secret
metadata:
  name: mattermost-external-db
  namespace: mattermost
type: Opaque
stringData:
  # Required: Connection string WITH protocol prefix (mysql:// or postgres://)
  # Used for MM_CONFIG environment variable
  DB_CONNECTION_STRING: "mysql://mmuser:mmpassword@tcp(mysql.example.com:3306)/mattermost?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s"
  
  # Optional but Recommended: Connection string WITHOUT protocol prefix
  # Used for MM_SQLSETTINGS_DATASOURCE environment variable
  # If not provided, falls back to DB_CONNECTION_STRING for backward compatibility
  MM_SQLSETTINGS_DATASOURCE: "mmuser:mmpassword@tcp(mysql.example.com:3306)/mattermost?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s"
  
  # Optional: Read replica endpoints (also without prefix)
  # Used for MM_SQLSETTINGS_DATASOURCEREPLICAS environment variable
  MM_SQLSETTINGS_DATASOURCEREPLICAS: "mmuser:mmpassword@tcp(mysql-replica.example.com:3306)/mattermost?readTimeout=30s&writeTimeout=30s"
  
  # Optional: Database health check URL
  # Used by init container to verify database readiness before starting Mattermost
  DB_CONNECTION_CHECK_URL: "http://mysql.example.com:3306"

---
# Example for PostgreSQL
apiVersion: v1
kind: Secret
metadata:
  name: mattermost-external-postgres
  namespace: mattermost
type: Opaque
stringData:
  # PostgreSQL with protocol prefix
  DB_CONNECTION_STRING: "postgres://mmuser:mmpassword@postgres.example.com:5432/mattermost?sslmode=require&connect_timeout=10"
  
  # PostgreSQL without protocol prefix
  MM_SQLSETTINGS_DATASOURCE: "mmuser:mmpassword@postgres.example.com:5432/mattermost?sslmode=require&connect_timeout=10"
  
  # Optional: PostgreSQL read replicas
  MM_SQLSETTINGS_DATASOURCEREPLICAS: "mmuser:mmpassword@postgres-replica.example.com:5432/mattermost?sslmode=require"
  
  # Optional: PostgreSQL health check (for pg_isready)
  DB_CONNECTION_CHECK_URL: "postgres://mmuser:mmpassword@postgres.example.com:5432/mattermost"

