// Copyright (c) 2017-present Mattermost, Inc. All Rights Reserved.
// See License.txt for license information.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	mattermostv1alpha1 "github.com/mattermost/mattermost-operator/apis/mattermost/v1alpha1"
	versioned "github.com/mattermost/mattermost-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/mattermost/mattermost-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/mattermost/mattermost-operator/pkg/client/listers/mattermost/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterInstallationInformer provides access to a shared informer and lister for
// ClusterInstallations.
type ClusterInstallationInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ClusterInstallationLister
}

type clusterInstallationInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewClusterInstallationInformer constructs a new informer for ClusterInstallation type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterInstallationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClusterInstallationInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredClusterInstallationInformer constructs a new informer for ClusterInstallation type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterInstallationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MattermostV1alpha1().ClusterInstallations(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MattermostV1alpha1().ClusterInstallations(namespace).Watch(context.TODO(), options)
			},
		},
		&mattermostv1alpha1.ClusterInstallation{},
		resyncPeriod,
		indexers,
	)
}

func (f *clusterInstallationInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClusterInstallationInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clusterInstallationInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&mattermostv1alpha1.ClusterInstallation{}, f.defaultInformer)
}

func (f *clusterInstallationInformer) Lister() v1alpha1.ClusterInstallationLister {
	return v1alpha1.NewClusterInstallationLister(f.Informer().GetIndexer())
}
