{{- if and .Values.mysqlOperator.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysqlOperator.appName }}-operator-orc
  namespace: {{ .Values.mysqlOperator.appName }}-operator
  labels:
    app: {{ .Values.mysqlOperator.appName }}-operator
    release: {{ .Values.mysqlOperator.appName }}-operator
data:
  TOPOLOGY_USER: {{ .Values.mysqlOperator.topology.user }}
  TOPOLOGY_PASSWORD: {{ .Values.mysqlOperator.topology.password }}
{{- end }}
