{{- if and .Values.mysqlOperator.enabled .Values.mysqlOperator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.mysqlOperator.appName }}-operator
  namespace: {{ .Values.mysqlOperator.appName }}-operator
  labels:
    app: {{ .Values.mysqlOperator.appName }}-operator
    release: {{ .Values.mysqlOperator.appName }}-operator
{{- end }}
