apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: mattermost-dev
  namespace: mattermost
spec:
  image: dev-registry:5000/mattermost-server
  version: dev
  replicas: 1
  imagePullPolicy: Always
  ingress:
    enabled: false
  database:
    external:
      secret: mm-db
  fileStore:
    local:
      enabled: true
      storageSize: 1Gi
      accessModes:
        - ReadWriteOnce
  mattermostEnv:
    - name: MM_SERVICESETTINGS_SITEURL
      value: "http://localhost:8065"
    - name: MM_SERVICESETTINGS_LISTENADDRESS
      value: ":8065"
    - name: MM_TRAILAGENTSETTINGS_ENABLE
      value: "true"
    - name: MM_TRAILAGENTSETTINGS_NAMESPACE
      value: "mattermost"
    - name: MM_SERVICESETTINGS_ENABLEBOTACCOUNTCREATION
      value: "true"
    - name: MM_SERVICESETTINGS_ENABLEUSERACCESSTOKENS
      value: "true"
