// Copyright (c) 2017-present Mattermost, Inc. All Rights Reserved.
// See License.txt for license information.

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	internalinterfaces "github.com/mattermost/mattermost-operator/pkg/client/v1beta1/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Mattermosts returns a MattermostInformer.
	Mattermosts() MattermostInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Mattermosts returns a MattermostInformer.
func (v *version) Mattermosts() MattermostInformer {
	return &mattermostInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
