/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/mattermost/mattermost-operator/pkg/apis/mattermost/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBlueGreens implements BlueGreenInterface
type FakeBlueGreens struct {
	Fake *FakeMattermostV1alpha1
	ns   string
}

var bluegreensResource = schema.GroupVersionResource{Group: "mattermost.com", Version: "v1alpha1", Resource: "bluegreens"}

var bluegreensKind = schema.GroupVersionKind{Group: "mattermost.com", Version: "v1alpha1", Kind: "BlueGreen"}

// Get takes name of the blueGreen, and returns the corresponding blueGreen object, and an error if there is any.
func (c *FakeBlueGreens) Get(name string, options v1.GetOptions) (result *v1alpha1.BlueGreen, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(bluegreensResource, c.ns, name), &v1alpha1.BlueGreen{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BlueGreen), err
}

// List takes label and field selectors, and returns the list of BlueGreens that match those selectors.
func (c *FakeBlueGreens) List(opts v1.ListOptions) (result *v1alpha1.BlueGreenList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(bluegreensResource, bluegreensKind, c.ns, opts), &v1alpha1.BlueGreenList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BlueGreenList{ListMeta: obj.(*v1alpha1.BlueGreenList).ListMeta}
	for _, item := range obj.(*v1alpha1.BlueGreenList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested blueGreens.
func (c *FakeBlueGreens) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(bluegreensResource, c.ns, opts))

}

// Create takes the representation of a blueGreen and creates it.  Returns the server's representation of the blueGreen, and an error, if there is any.
func (c *FakeBlueGreens) Create(blueGreen *v1alpha1.BlueGreen) (result *v1alpha1.BlueGreen, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(bluegreensResource, c.ns, blueGreen), &v1alpha1.BlueGreen{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BlueGreen), err
}

// Update takes the representation of a blueGreen and updates it. Returns the server's representation of the blueGreen, and an error, if there is any.
func (c *FakeBlueGreens) Update(blueGreen *v1alpha1.BlueGreen) (result *v1alpha1.BlueGreen, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(bluegreensResource, c.ns, blueGreen), &v1alpha1.BlueGreen{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BlueGreen), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBlueGreens) UpdateStatus(blueGreen *v1alpha1.BlueGreen) (*v1alpha1.BlueGreen, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(bluegreensResource, "status", c.ns, blueGreen), &v1alpha1.BlueGreen{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BlueGreen), err
}

// Delete takes name of the blueGreen and deletes it. Returns an error if one occurs.
func (c *FakeBlueGreens) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(bluegreensResource, c.ns, name), &v1alpha1.BlueGreen{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBlueGreens) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(bluegreensResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.BlueGreenList{})
	return err
}

// Patch applies the patch and returns the patched blueGreen.
func (c *FakeBlueGreens) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.BlueGreen, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(bluegreensResource, c.ns, name, pt, data, subresources...), &v1alpha1.BlueGreen{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BlueGreen), err
}
