// Copyright (c) 2017-present Mattermost, Inc. All Rights Reserved.
// See License.txt for license information.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/mattermost/mattermost-operator/apis/mattermost/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterInstallations implements ClusterInstallationInterface
type FakeClusterInstallations struct {
	Fake *FakeMattermostV1alpha1
	ns   string
}

var clusterinstallationsResource = schema.GroupVersionResource{Group: "mattermost.com", Version: "v1alpha1", Resource: "clusterinstallations"}

var clusterinstallationsKind = schema.GroupVersionKind{Group: "mattermost.com", Version: "v1alpha1", Kind: "ClusterInstallation"}

// Get takes name of the clusterInstallation, and returns the corresponding clusterInstallation object, and an error if there is any.
func (c *FakeClusterInstallations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterInstallation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(clusterinstallationsResource, c.ns, name), &v1alpha1.ClusterInstallation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterInstallation), err
}

// List takes label and field selectors, and returns the list of ClusterInstallations that match those selectors.
func (c *FakeClusterInstallations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterInstallationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(clusterinstallationsResource, clusterinstallationsKind, c.ns, opts), &v1alpha1.ClusterInstallationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterInstallationList{ListMeta: obj.(*v1alpha1.ClusterInstallationList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterInstallationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterInstallations.
func (c *FakeClusterInstallations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(clusterinstallationsResource, c.ns, opts))

}

// Create takes the representation of a clusterInstallation and creates it.  Returns the server's representation of the clusterInstallation, and an error, if there is any.
func (c *FakeClusterInstallations) Create(ctx context.Context, clusterInstallation *v1alpha1.ClusterInstallation, opts v1.CreateOptions) (result *v1alpha1.ClusterInstallation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(clusterinstallationsResource, c.ns, clusterInstallation), &v1alpha1.ClusterInstallation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterInstallation), err
}

// Update takes the representation of a clusterInstallation and updates it. Returns the server's representation of the clusterInstallation, and an error, if there is any.
func (c *FakeClusterInstallations) Update(ctx context.Context, clusterInstallation *v1alpha1.ClusterInstallation, opts v1.UpdateOptions) (result *v1alpha1.ClusterInstallation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(clusterinstallationsResource, c.ns, clusterInstallation), &v1alpha1.ClusterInstallation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterInstallation), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterInstallations) UpdateStatus(ctx context.Context, clusterInstallation *v1alpha1.ClusterInstallation, opts v1.UpdateOptions) (*v1alpha1.ClusterInstallation, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(clusterinstallationsResource, "status", c.ns, clusterInstallation), &v1alpha1.ClusterInstallation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterInstallation), err
}

// Delete takes name of the clusterInstallation and deletes it. Returns an error if one occurs.
func (c *FakeClusterInstallations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(clusterinstallationsResource, c.ns, name), &v1alpha1.ClusterInstallation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterInstallations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(clusterinstallationsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterInstallationList{})
	return err
}

// Patch applies the patch and returns the patched clusterInstallation.
func (c *FakeClusterInstallations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterInstallation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(clusterinstallationsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ClusterInstallation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterInstallation), err
}
