{{- if and .Values.minioOperator.enabled .Values.minioOperator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.minioOperator.appName }}-operator-sa
  namespace: {{ .Values.minioOperator.appName }}-operator
{{- end }}
