// Copyright (c) 2017-present Mattermost, Inc. All Rights Reserved.
// See License.txt for license information.

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/mattermost/mattermost-operator/apis/mattermost/v1beta1"
	scheme "github.com/mattermost/mattermost-operator/pkg/client/v1beta1/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MattermostsGetter has a method to return a MattermostInterface.
// A group's client should implement this interface.
type MattermostsGetter interface {
	Mattermosts(namespace string) MattermostInterface
}

// MattermostInterface has methods to work with Mattermost resources.
type MattermostInterface interface {
	Create(ctx context.Context, mattermost *v1beta1.Mattermost, opts v1.CreateOptions) (*v1beta1.Mattermost, error)
	Update(ctx context.Context, mattermost *v1beta1.Mattermost, opts v1.UpdateOptions) (*v1beta1.Mattermost, error)
	UpdateStatus(ctx context.Context, mattermost *v1beta1.Mattermost, opts v1.UpdateOptions) (*v1beta1.Mattermost, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.Mattermost, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.MattermostList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.Mattermost, err error)
	MattermostExpansion
}

// mattermosts implements MattermostInterface
type mattermosts struct {
	client rest.Interface
	ns     string
}

// newMattermosts returns a Mattermosts
func newMattermosts(c *MattermostV1beta1Client, namespace string) *mattermosts {
	return &mattermosts{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the mattermost, and returns the corresponding mattermost object, and an error if there is any.
func (c *mattermosts) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.Mattermost, err error) {
	result = &v1beta1.Mattermost{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mattermosts").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Mattermosts that match those selectors.
func (c *mattermosts) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.MattermostList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.MattermostList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mattermosts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested mattermosts.
func (c *mattermosts) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("mattermosts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a mattermost and creates it.  Returns the server's representation of the mattermost, and an error, if there is any.
func (c *mattermosts) Create(ctx context.Context, mattermost *v1beta1.Mattermost, opts v1.CreateOptions) (result *v1beta1.Mattermost, err error) {
	result = &v1beta1.Mattermost{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("mattermosts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(mattermost).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a mattermost and updates it. Returns the server's representation of the mattermost, and an error, if there is any.
func (c *mattermosts) Update(ctx context.Context, mattermost *v1beta1.Mattermost, opts v1.UpdateOptions) (result *v1beta1.Mattermost, err error) {
	result = &v1beta1.Mattermost{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("mattermosts").
		Name(mattermost.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(mattermost).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *mattermosts) UpdateStatus(ctx context.Context, mattermost *v1beta1.Mattermost, opts v1.UpdateOptions) (result *v1beta1.Mattermost, err error) {
	result = &v1beta1.Mattermost{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("mattermosts").
		Name(mattermost.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(mattermost).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the mattermost and deletes it. Returns an error if one occurs.
func (c *mattermosts) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mattermosts").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *mattermosts) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mattermosts").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched mattermost.
func (c *mattermosts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.Mattermost, err error) {
	result = &v1beta1.Mattermost{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("mattermosts").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
