// Copyright (c) 2017-present Mattermost, Inc. All Rights Reserved.
// See License.txt for license information.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/mattermost/mattermost-operator/apis/mattermost/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMattermosts implements MattermostInterface
type FakeMattermosts struct {
	Fake *FakeMattermostV1beta1
	ns   string
}

var mattermostsResource = schema.GroupVersionResource{Group: "mattermost", Version: "v1beta1", Resource: "mattermosts"}

var mattermostsKind = schema.GroupVersionKind{Group: "mattermost", Version: "v1beta1", Kind: "Mattermost"}

// Get takes name of the mattermost, and returns the corresponding mattermost object, and an error if there is any.
func (c *FakeMattermosts) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.Mattermost, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(mattermostsResource, c.ns, name), &v1beta1.Mattermost{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Mattermost), err
}

// List takes label and field selectors, and returns the list of Mattermosts that match those selectors.
func (c *FakeMattermosts) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.MattermostList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(mattermostsResource, mattermostsKind, c.ns, opts), &v1beta1.MattermostList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.MattermostList{ListMeta: obj.(*v1beta1.MattermostList).ListMeta}
	for _, item := range obj.(*v1beta1.MattermostList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested mattermosts.
func (c *FakeMattermosts) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(mattermostsResource, c.ns, opts))

}

// Create takes the representation of a mattermost and creates it.  Returns the server's representation of the mattermost, and an error, if there is any.
func (c *FakeMattermosts) Create(ctx context.Context, mattermost *v1beta1.Mattermost, opts v1.CreateOptions) (result *v1beta1.Mattermost, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(mattermostsResource, c.ns, mattermost), &v1beta1.Mattermost{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Mattermost), err
}

// Update takes the representation of a mattermost and updates it. Returns the server's representation of the mattermost, and an error, if there is any.
func (c *FakeMattermosts) Update(ctx context.Context, mattermost *v1beta1.Mattermost, opts v1.UpdateOptions) (result *v1beta1.Mattermost, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(mattermostsResource, c.ns, mattermost), &v1beta1.Mattermost{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Mattermost), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMattermosts) UpdateStatus(ctx context.Context, mattermost *v1beta1.Mattermost, opts v1.UpdateOptions) (*v1beta1.Mattermost, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(mattermostsResource, "status", c.ns, mattermost), &v1beta1.Mattermost{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Mattermost), err
}

// Delete takes name of the mattermost and deletes it. Returns an error if one occurs.
func (c *FakeMattermosts) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(mattermostsResource, c.ns, name, opts), &v1beta1.Mattermost{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMattermosts) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(mattermostsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.MattermostList{})
	return err
}

// Patch applies the patch and returns the patched mattermost.
func (c *FakeMattermosts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.Mattermost, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mattermostsResource, c.ns, name, pt, data, subresources...), &v1beta1.Mattermost{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Mattermost), err
}
