// Copyright (c) 2017-present Mattermost, Inc. All Rights Reserved.
// See License.txt for license information.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type ClusterInstallationExpansion interface{}
