// Copyright (c) 2017-present Mattermost, Inc. All Rights Reserved.
// See License.txt for license information.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/mattermost/mattermost-operator/pkg/apis/mattermost/v1alpha1"
	"github.com/mattermost/mattermost-operator/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type MattermostV1alpha1Interface interface {
	RESTClient() rest.Interface
	ClusterInstallationsGetter
}

// MattermostV1alpha1Client is used to interact with features provided by the mattermost.com group.
type MattermostV1alpha1Client struct {
	restClient rest.Interface
}

func (c *MattermostV1alpha1Client) ClusterInstallations(namespace string) ClusterInstallationInterface {
	return newClusterInstallations(c, namespace)
}

// NewForConfig creates a new MattermostV1alpha1Client for the given config.
func NewForConfig(c *rest.Config) (*MattermostV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &MattermostV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new MattermostV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *MattermostV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new MattermostV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *MattermostV1alpha1Client {
	return &MattermostV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *MattermostV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
