// Copyright (c) 2017-present Mattermost, Inc. All Rights Reserved.
// See License.txt for license information.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/mattermost/mattermost-operator/pkg/client/v1beta1/clientset/versioned/typed/mattermost/v1beta1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeMattermostV1beta1 struct {
	*testing.Fake
}

func (c *FakeMattermostV1beta1) Mattermosts(namespace string) v1beta1.MattermostInterface {
	return &FakeMattermosts{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeMattermostV1beta1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
